[package]
name = "blog_target_cpu"
version = "1.0.0"
authors = ["Nick Wilcox <nick@nickwilcox.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
rand = "0.7.3"

[profile.dev.package."*"]
opt-level = 3
 
[[bench]]
name = "benchmark"
harness = false
